# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # 1. Maintain Python dependencies via uv
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
      - "dependencies"

  # 2. Maintain GitHub Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
      - "dependencies"

  # 3. Maintain local Git hooks
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "chore"
      - "dependencies"
